version: '3.1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: always
    volumes:
      - ./laravel-app:/var/www/html
    ports:
      - "8000:80"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laraveluser
      - DB_PASSWORD=yourpassword
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: mariadb_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=yourpassword
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=localuser
      - MYSQL_PASSWORD=localuser
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: