version: '3.1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: always
    volumes:
      - ./:/var/www/html
    ports:
      - "8000:80"
      - "8001:5173"
    # use .env for environment variables
    env_file:
      - ./laravel-app/.env
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: mariadb_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=yourpassword
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=localuser
      - MYSQL_PASSWORD=localuser
    volumes:
      - mariadb_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8002:8080"

volumes:
  mariadb_data: